POST http://localhost:3001/api/notes 
Content-Type: application/json

{
  "content": "Funciona xD",
  "important": true
}

####

POST http://localhost:3001/api/notes 
Content-Type: application/json

{
}