POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzM2U4NjAwNjEwN2FkNjkzMDUxODI3ZiIsInVzZXJuYW1lIjoiY2hhcmRzZGV2IiwiaWF0IjoxNjY1MTExNzkxLCJleHAiOjE2NjU3MTY1OTF9.45vCanPptAvwr0mkVGCkhZw_Oz_c9DQSOVX6-_IUfCQ

{
  "content": "Probando con controllers nota 2 para chards",
  "important": true
}

####

POST http://localhost:3001/api/notes 
Content-Type: application/json

{
}